// @generated by `make generate-proto` from proto/monty/v1/monty.proto — DO NOT EDIT.
#![allow(
    clippy::allow_attributes,
    clippy::pedantic,
    clippy::use_self,
    clippy::absolute_paths,
    missing_docs,
    dead_code
)]
// This file is @generated by prost-build.
/// Empty placeholder for valueless oneof arms. Defined locally (rather than
/// importing google.protobuf.Empty) so non-Rust decoders need nothing beyond
/// this single file.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Unit {}
/// A Python value crossing the sandbox boundary. Mirrors monty's `MontyObject`
/// enum variant-for-variant.
///
/// `repr` and `cycle` are OUTPUT-ONLY: the child may emit them (e.g. inside a
/// `Complete` value) but rejects them as inputs, exactly like `MontyObject`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MontyObject {
    #[prost(
        oneof = "monty_object::Kind",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27"
    )]
    pub kind: ::core::option::Option<monty_object::Kind>,
}
/// Nested message and enum types in `MontyObject`.
pub mod monty_object {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Ellipsis(super::Unit),
        #[prost(message, tag = "2")]
        None(super::Unit),
        #[prost(bool, tag = "3")]
        Boolean(bool),
        /// Python int fitting in 64 bits.
        #[prost(sint64, tag = "4")]
        Int(i64),
        /// Python int wider than 64 bits.
        #[prost(message, tag = "5")]
        Bigint(super::BigInt),
        #[prost(double, tag = "6")]
        Float(f64),
        #[prost(string, tag = "7")]
        Str(::prost::alloc::string::String),
        #[prost(bytes, tag = "8")]
        Bytes(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "9")]
        List(super::ObjectList),
        #[prost(message, tag = "10")]
        Tuple(super::ObjectList),
        #[prost(message, tag = "11")]
        NamedTuple(super::NamedTuple),
        #[prost(message, tag = "12")]
        Dict(super::Dict),
        #[prost(message, tag = "13")]
        Set(super::ObjectList),
        #[prost(message, tag = "14")]
        FrozenSet(super::ObjectList),
        #[prost(message, tag = "15")]
        Date(super::Date),
        #[prost(message, tag = "16")]
        Datetime(super::DateTime),
        #[prost(message, tag = "17")]
        Timedelta(super::TimeDelta),
        #[prost(message, tag = "18")]
        Timezone(super::TimeZone),
        /// A simple exception VALUE (no traceback) — e.g. an exception stored in a
        /// variable. Errors that terminate execution use `RaisedException` instead.
        #[prost(message, tag = "19")]
        Exception(super::Exception),
        /// A Python type object, named by monty's `Type` Display string, e.g.
        /// "int", "str", "datetime.datetime", "ValueError".
        #[prost(string, tag = "20")]
        Type(::prost::alloc::string::String),
        /// A builtin function, named by its Python name, e.g. "len", "print".
        #[prost(string, tag = "21")]
        BuiltinFunction(::prost::alloc::string::String),
        /// A pathlib.Path value (always a virtual POSIX path, never a host path).
        #[prost(string, tag = "22")]
        Path(::prost::alloc::string::String),
        #[prost(message, tag = "23")]
        FileHandle(super::FileHandle),
        #[prost(message, tag = "24")]
        Dataclass(super::Dataclass),
        #[prost(message, tag = "25")]
        Function(super::Function),
        /// OUTPUT-ONLY fallback: repr() of a value with no other representation.
        #[prost(string, tag = "26")]
        Repr(::prost::alloc::string::String),
        /// OUTPUT-ONLY marker breaking reference cycles in container output.
        #[prost(message, tag = "27")]
        Cycle(super::Cycle),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectList {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<MontyObject>,
}
/// One key/value entry. Used for dicts and kwargs: proto maps cannot have
/// message keys and do not preserve order, while Python dicts allow arbitrary
/// hashable keys and are insertion-ordered.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pair {
    #[prost(message, optional, tag = "1")]
    pub key: ::core::option::Option<MontyObject>,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<MontyObject>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dict {
    #[prost(message, repeated, tag = "1")]
    pub pairs: ::prost::alloc::vec::Vec<Pair>,
}
/// Arbitrary-precision integer as sign + big-endian magnitude. Exact and O(n);
/// JS decode is `(negative ? -1n : 1n) * BigInt('0x' + hex(magnitude))`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BigInt {
    #[prost(bool, tag = "1")]
    pub negative: bool,
    #[prost(bytes = "vec", tag = "2")]
    pub magnitude: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NamedTuple {
    /// Type name used in repr, e.g. "os.stat_result".
    #[prost(string, tag = "1")]
    pub type_name: ::prost::alloc::string::String,
    /// Attribute names, one per value.
    #[prost(string, repeated, tag = "2")]
    pub field_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "3")]
    pub values: ::prost::alloc::vec::Vec<MontyObject>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Date {
    /// Gregorian year in 1..=9999.
    #[prost(int32, tag = "1")]
    pub year: i32,
    /// 1..=12.
    #[prost(uint32, tag = "2")]
    pub month: u32,
    #[prost(uint32, tag = "3")]
    pub day: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DateTime {
    #[prost(int32, tag = "1")]
    pub year: i32,
    #[prost(uint32, tag = "2")]
    pub month: u32,
    #[prost(uint32, tag = "3")]
    pub day: u32,
    #[prost(uint32, tag = "4")]
    pub hour: u32,
    #[prost(uint32, tag = "5")]
    pub minute: u32,
    #[prost(uint32, tag = "6")]
    pub second: u32,
    /// 0..=999999.
    #[prost(uint32, tag = "7")]
    pub microsecond: u32,
    /// Fixed UTC offset for aware datetimes; absent for naive values.
    #[prost(int32, optional, tag = "8")]
    pub offset_seconds: ::core::option::Option<i32>,
    /// Optional timezone name; only valid when offset_seconds is set.
    #[prost(string, optional, tag = "9")]
    pub timezone_name: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimeDelta {
    #[prost(int32, tag = "1")]
    pub days: i32,
    /// Normalized to 0..86400.
    #[prost(int32, tag = "2")]
    pub seconds: i32,
    /// Normalized to 0..1000000.
    #[prost(int32, tag = "3")]
    pub microseconds: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimeZone {
    #[prost(int32, tag = "1")]
    pub offset_seconds: i32,
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
}
/// A simple exception value: type name (e.g. "ValueError") + optional single
/// string argument.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Exception {
    #[prost(string, tag = "1")]
    pub exc_type: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub arg: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileHandle {
    /// Virtual (sandbox) path — never a host path.
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    /// Canonical Python open() mode string: one of r, rb, r+, rb+, w, wb, w+,
    /// wb+, a, ab, a+, ab+.
    #[prost(string, tag = "2")]
    pub mode: ::prost::alloc::string::String,
    /// Char index (text mode) or byte index (binary mode).
    #[prost(uint64, tag = "3")]
    pub position: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dataclass {
    /// Class name, e.g. "Point".
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Host-side identity of the class, from `id(type(dc))`.
    #[prost(uint64, tag = "2")]
    pub type_id: u64,
    /// Declared field names in definition order.
    #[prost(string, repeated, tag = "3")]
    pub field_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// All attributes (fields and extras), in order.
    #[prost(message, optional, tag = "4")]
    pub attrs: ::core::option::Option<Dict>,
    #[prost(bool, tag = "5")]
    pub frozen: bool,
}
/// An external (host-provided) function value, usually supplied by the parent
/// in response to a `NameLookup` event.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Function {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub docstring: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Cycle {
    /// Opaque identity token for the object the cycle refers back to: two
    /// cycle markers in the same result are the same object iff their tokens
    /// match. Meaningless outside the result that produced it.
    #[prost(uint64, tag = "1")]
    pub identity: u64,
    /// Type-specific placeholder shown in reprs, e.g. "\[...\]".
    #[prost(string, tag = "2")]
    pub placeholder: ::prost::alloc::string::String,
}
/// A raised Python exception with its traceback. Mirrors monty's
/// `MontyException`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RaisedException {
    /// Exception type name, e.g. "ValueError", "json.JSONDecodeError".
    #[prost(string, tag = "1")]
    pub exc_type: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
    /// Outermost frame first, matching Python traceback order.
    #[prost(message, repeated, tag = "3")]
    pub traceback: ::prost::alloc::vec::Vec<StackFrame>,
    /// Structured payload for exception types that carry more than a message;
    /// absent for most exceptions. Mirrors monty's `ExcData`.
    #[prost(message, optional, tag = "4")]
    pub data: ::core::option::Option<ExcData>,
}
/// Structured exception payload, mirroring monty's `ExcData` enum. Future
/// exception types that carry more than a message (e.g. OSError's errno)
/// get new oneof arms with fresh tags. An absent/empty kind means "no
/// payload" (`ExcData::None`).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExcData {
    #[prost(oneof = "exc_data::Kind", tags = "1")]
    pub kind: ::core::option::Option<exc_data::Kind>,
}
/// Nested message and enum types in `ExcData`.
pub mod exc_data {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Unicode(super::UnicodeErrorData),
    }
}
/// CPython's UnicodeDecodeError/UnicodeEncodeError constructor fields
/// (encoding, object, start, end, reason), letting hosts rebuild the real
/// exception instead of a message-only fallback. Mirrors monty's
/// `UnicodeErrorData`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnicodeErrorData {
    /// Codec name as CPython reports it, e.g. "utf-8".
    #[prost(string, tag = "1")]
    pub encoding: ::prost::alloc::string::String,
    /// Failing range: byte offsets for decode errors, character indices for
    /// encode errors. `end` is exclusive.
    #[prost(uint64, tag = "4")]
    pub start: u64,
    #[prost(uint64, tag = "5")]
    pub end: u64,
    /// CPython's reason wording, e.g. "ordinal not in range(128)".
    #[prost(string, tag = "6")]
    pub reason: ::prost::alloc::string::String,
    /// The input that failed: bytes for decode errors, str for encode errors.
    #[prost(oneof = "unicode_error_data::Object", tags = "2, 3")]
    pub object: ::core::option::Option<unicode_error_data::Object>,
}
/// Nested message and enum types in `UnicodeErrorData`.
pub mod unicode_error_data {
    /// The input that failed: bytes for decode errors, str for encode errors.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Object {
        #[prost(bytes, tag = "2")]
        ObjectBytes(::prost::alloc::vec::Vec<u8>),
        #[prost(string, tag = "3")]
        ObjectStr(::prost::alloc::string::String),
    }
}
/// 1-based line/column source position (columns count characters, not bytes).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CodeLoc {
    #[prost(uint32, tag = "1")]
    pub line: u32,
    #[prost(uint32, tag = "2")]
    pub column: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StackFrame {
    #[prost(string, tag = "1")]
    pub filename: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub start: ::core::option::Option<CodeLoc>,
    #[prost(message, optional, tag = "3")]
    pub end: ::core::option::Option<CodeLoc>,
    /// Function name; absent for module-level code (rendered as "<module>").
    #[prost(string, optional, tag = "4")]
    pub frame_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Source line shown in the traceback preview.
    #[prost(string, optional, tag = "5")]
    pub preview_line: ::core::option::Option<::prost::alloc::string::String>,
    /// Suppress the `~~~` caret markers for this frame.
    #[prost(bool, tag = "6")]
    pub hide_caret: bool,
    /// Suppress the `, in <name>` suffix (SyntaxError style).
    #[prost(bool, tag = "7")]
    pub hide_frame_name: bool,
}
/// Sandbox resource limits, enforced inside the child. Absent fields mean
/// "unlimited" except recursion depth, which defaults to monty's standard
/// limit (1000) when absent.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResourceLimits {
    #[prost(uint64, optional, tag = "1")]
    pub max_allocations: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    pub max_duration_micros: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "3")]
    pub max_memory_bytes: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "4")]
    pub gc_interval: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "5")]
    pub max_recursion_depth: ::core::option::Option<u64>,
}
/// Mounts a host directory into the sandbox. The child builds its own
/// MountTable from these, so the host path must be valid on the machine the
/// child runs on.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Mount {
    /// Absolute virtual POSIX path, e.g. "/mnt/data".
    #[prost(string, tag = "1")]
    pub virtual_path: ::prost::alloc::string::String,
    /// Host-native directory path.
    #[prost(string, tag = "2")]
    pub host_path: ::prost::alloc::string::String,
    #[prost(enumeration = "MountMode", tag = "3")]
    pub mode: i32,
    /// Cap on total bytes written through this mount.
    #[prost(uint64, optional, tag = "4")]
    pub write_bytes_limit: ::core::option::Option<u64>,
}
/// Outcome of an external function / OS call, decided by the parent. Mirrors
/// monty's `ExtFunctionResult`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExtFunctionResult {
    #[prost(oneof = "ext_function_result::Kind", tags = "1, 2, 3, 4")]
    pub kind: ::core::option::Option<ext_function_result::Kind>,
}
/// Nested message and enum types in `ExtFunctionResult`.
pub mod ext_function_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        /// The call returned this value.
        #[prost(message, tag = "1")]
        ReturnValue(super::MontyObject),
        /// The call raised this exception.
        #[prost(message, tag = "2")]
        Error(super::RaisedException),
        /// The call is asynchronous: register an external future for `call_id`
        /// (the id from the suspension event) and keep executing other tasks.
        #[prost(uint32, tag = "3")]
        Future(u32),
        /// No handler exists for this name — the child raises NameError.
        #[prost(string, tag = "4")]
        NotFound(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FutureResult {
    #[prost(uint32, tag = "1")]
    pub call_id: u32,
    #[prost(message, optional, tag = "2")]
    pub result: ::core::option::Option<ExtFunctionResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NamedValue {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<MontyObject>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParentRequest {
    #[prost(oneof = "parent_request::Kind", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10")]
    pub kind: ::core::option::Option<parent_request::Kind>,
}
/// Nested message and enum types in `ParentRequest`.
pub mod parent_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Configure(super::Configure),
        #[prost(message, tag = "2")]
        InstallDependencies(super::InstallDependencies),
        #[prost(message, tag = "3")]
        Feed(super::Feed),
        #[prost(message, tag = "4")]
        ResumeCall(super::ResumeCall),
        #[prost(message, tag = "5")]
        ResumeNameLookup(super::ResumeNameLookup),
        #[prost(message, tag = "6")]
        ResumeFutures(super::ResumeFutures),
        #[prost(message, tag = "7")]
        Dump(super::Dump),
        #[prost(message, tag = "8")]
        Load(super::Load),
        #[prost(message, tag = "9")]
        Reset(super::Reset),
        #[prost(message, tag = "10")]
        Shutdown(super::Shutdown),
    }
}
/// Configures the REPL session this child will serve until `Reset`, sent once
/// when the worker is checked out. The session's repl is materialized lazily on
/// the first `Feed` (or restored by `Load`), so a checked-out-but-unfed
/// worker can still be initialized by `Load` instead. Valid only when the
/// worker has no session yet.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Configure {
    #[prost(string, tag = "1")]
    pub script_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub limits: ::core::option::Option<ResourceLimits>,
    /// Type-check each fed snippet before executing it.
    #[prost(bool, tag = "3")]
    pub type_check: bool,
    /// Optional stub file contents used by type checking.
    #[prost(string, optional, tag = "4")]
    pub type_check_stubs: ::core::option::Option<::prost::alloc::string::String>,
    /// The parent's monty version (e.g. "0.0.18"). The child rejects the
    /// session with a `FatalError` when this does not match its own version:
    /// the protocol has no in-band negotiation and parent and child must be
    /// deployed in lockstep, so a mismatch is a hard, fail-fast error rather
    /// than a silent source of frame desync.
    #[prost(string, tag = "5")]
    pub monty_version: ::prost::alloc::string::String,
}
/// Executes one snippet against the session. Turn ends with `Complete`,
/// `Error`, `TypingError`, or a suspension event.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Feed {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub inputs: ::prost::alloc::vec::Vec<NamedValue>,
    /// Mounts for this feed; handled entirely inside the child. OS calls the
    /// mounts do not cover bubble up as `OsCall` events.
    #[prost(message, repeated, tag = "3")]
    pub mounts: ::prost::alloc::vec::Vec<Mount>,
    /// Skip type checking for this feed even when the session enables it.
    #[prost(bool, tag = "4")]
    pub skip_type_check: bool,
}
/// Answers a `FunctionCall` or `OsCall` suspension. `call_id` must match the
/// suspension event.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResumeCall {
    #[prost(uint32, tag = "1")]
    pub call_id: u32,
    #[prost(message, optional, tag = "2")]
    pub result: ::core::option::Option<ExtFunctionResult>,
}
/// Answers a `NameLookup` suspension.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResumeNameLookup {
    #[prost(oneof = "resume_name_lookup::Kind", tags = "1, 2")]
    pub kind: ::core::option::Option<resume_name_lookup::Kind>,
}
/// Nested message and enum types in `ResumeNameLookup`.
pub mod resume_name_lookup {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        /// The name resolves to this value.
        #[prost(message, tag = "1")]
        Value(super::MontyObject),
        /// The name is undefined — the child raises NameError.
        #[prost(message, tag = "2")]
        Undefined(super::Unit),
    }
}
/// Answers a `ResolveFutures` suspension with results for some or all pending
/// call ids.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResumeFutures {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<FutureResult>,
}
/// Requests an opaque serialized snapshot of the current session state
/// (idle or suspended). The child stays usable afterwards. The bytes can only
/// be restored by a monty child of the same version via `Load`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Dump {}
/// Restores state produced by `Dump`. Valid only from no session. If
/// the restored state was suspended, the child re-emits the suspension event so
/// the parent learns the resume point; otherwise it replies `Ok`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Load {
    #[prost(bytes = "vec", tag = "1")]
    pub state: ::prost::alloc::vec::Vec<u8>,
    /// Mounts to re-establish for a suspended feed being resumed. Mounts are
    /// host configuration, not sandbox state, so they are never part of the dump
    /// — the parent re-supplies the same mounts it used for the original feed.
    /// Without them a restored feed has no mounts and its OS calls all bubble up.
    /// When the restored state is idle this must be empty.
    #[prost(message, repeated, tag = "2")]
    pub mounts: ::prost::alloc::vec::Vec<Mount>,
}
/// Ends the checkout: the child drops all session state and returns to the
/// no-session state, ready for the next `Configure` or `Load`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Reset {}
/// The child replies `Ok` and exits cleanly.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Shutdown {}
/// Installs third-party Python packages into the session before further feeds,
/// using `uv pip install --python <venv-python>` against the worker's session
/// virtualenv. Only the
/// embedded-CPython worker honors this; the Monty sandbox child rejects it with
/// an `Error` (it has no host interpreter to install for). Repeatable between
/// feeds. Turn ends with `Ok` on success or `Error` (carrying uv's stderr) on
/// failure. Valid only once a session exists (after `Configure`).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InstallDependencies {
    /// PEP 508 requirement strings, e.g. "httpx>=0.27", "numpy". An empty list is
    /// a no-op that replies `Ok`.
    #[prost(string, repeated, tag = "1")]
    pub requirements: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChildEvent {
    /// Cumulative execution time consumed by the session's sandbox code, in
    /// microseconds. The in-sandbox clock runs only while the interpreter is
    /// executing bytecode — never while suspended waiting on the parent or idle
    /// between feeds — and survives Dump/Load. Set on every turn-ending event
    /// while a session exists (zero on Print events and outside a session) so
    /// the parent can mirror the `max_duration` budget, e.g. to arm a watchdog
    /// backstop, without keeping a second clock.
    #[prost(uint64, tag = "12")]
    pub total_execution_micros: u64,
    /// The session's `max_duration` limit in microseconds, when one is
    /// configured. Reported alongside `total_execution_micros` so a parent that
    /// restored a session via `Load` (where the limits travel inside the opaque
    /// state bytes) still learns the budget.
    #[prost(uint64, optional, tag = "13")]
    pub max_duration_micros: ::core::option::Option<u64>,
    /// The session's script name, surfaced on a `Load` reply so a parent that
    /// restored a session (whose script name, like the limits above, travels
    /// inside the opaque dump bytes) learns it without parsing the dump. Set only
    /// on a successful `Load` reply; unset on all other events.
    #[prost(string, optional, tag = "14")]
    pub restored_script_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof = "child_event::Kind", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11")]
    pub kind: ::core::option::Option<child_event::Kind>,
}
/// Nested message and enum types in `ChildEvent`.
pub mod child_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Print(super::Print),
        #[prost(message, tag = "2")]
        FunctionCall(super::FunctionCall),
        #[prost(message, tag = "3")]
        OsCall(super::OsCall),
        #[prost(message, tag = "4")]
        NameLookup(super::NameLookup),
        #[prost(message, tag = "5")]
        ResolveFutures(super::ResolveFutures),
        #[prost(message, tag = "6")]
        Complete(super::Complete),
        #[prost(message, tag = "7")]
        Error(super::Error),
        #[prost(message, tag = "8")]
        TypingError(super::TypingError),
        #[prost(message, tag = "9")]
        DumpResult(super::DumpResult),
        #[prost(message, tag = "10")]
        Ok(super::Ok),
        #[prost(message, tag = "11")]
        FatalError(super::FatalError),
    }
}
/// Streamed sandbox print() output. Zero or more of these precede each
/// turn-ending event; text is flushed at line granularity.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Print {
    #[prost(enumeration = "PrintStream", tag = "1")]
    pub stream: i32,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
}
/// Suspension: the sandbox called an external function (or a dataclass method
/// when `method_call` is true — the instance is then the first arg). Answer
/// with `ResumeCall`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionCall {
    #[prost(string, tag = "1")]
    pub function_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<MontyObject>,
    #[prost(message, repeated, tag = "3")]
    pub kwargs: ::prost::alloc::vec::Vec<Pair>,
    #[prost(uint32, tag = "4")]
    pub call_id: u32,
    #[prost(bool, tag = "5")]
    pub method_call: bool,
}
/// Suspension: the sandbox performed an OS operation no mount handled, e.g.
/// "Path.read_text" or "os.getenv". Answer with `ResumeCall`. Some calls have
/// typed result expectations (e.g. "Open" must return a file_handle); a
/// mismatched result becomes a Python-level error inside the sandbox.
///
/// NOTE: an OsCall re-announced after `Load` carries only `call_id` and
/// `not_handled_error` — the argument payload was consumed when the call was
/// first announced, before the dump was taken.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OsCall {
    #[prost(string, tag = "1")]
    pub function_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<MontyObject>,
    #[prost(message, repeated, tag = "3")]
    pub kwargs: ::prost::alloc::vec::Vec<Pair>,
    #[prost(uint32, tag = "4")]
    pub call_id: u32,
    /// The exception monty would raise for this call when nothing handles it
    /// (e.g. PermissionError for filesystem calls). A parent with no handler
    /// should answer `ResumeCall` with this error — only the child knows the
    /// per-call semantics.
    #[prost(message, optional, tag = "5")]
    pub not_handled_error: ::core::option::Option<RaisedException>,
}
/// Suspension: the sandbox read an undefined name — typically probing whether
/// the parent provides an external function. Answer with `ResumeNameLookup`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NameLookup {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
/// Suspension: every sandbox task is blocked on external futures previously
/// registered via `ExtFunctionResult.future`. Answer with `ResumeFutures`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveFutures {
    #[prost(uint32, repeated, tag = "1")]
    pub pending_call_ids: ::prost::alloc::vec::Vec<u32>,
}
/// Turn end: the snippet completed with this value. The session is ready for
/// the next `Feed`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Complete {
    #[prost(message, optional, tag = "1")]
    pub value: ::core::option::Option<MontyObject>,
}
/// Turn end: the snippet (or request) failed with a Python exception. The
/// session survives — prior globals remain available to later feeds.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    #[prost(message, optional, tag = "1")]
    pub exception: ::core::option::Option<RaisedException>,
}
/// Turn end: type checking rejected the fed snippet (only when the session
/// was created with type_check). The snippet was not executed; the session
/// survives.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TypingError {
    /// Rendered diagnostics, one per line.
    #[prost(string, tag = "1")]
    pub diagnostics: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DumpResult {
    /// Opaque versioned snapshot; see `Dump`.
    #[prost(bytes = "vec", tag = "1")]
    pub state: ::prost::alloc::vec::Vec<u8>,
}
/// Generic acknowledgement for Configure / Load (idle) / Reset / Shutdown.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ok {}
/// The child hit an unrecoverable error (frame desync, panic, unsupported
/// protocol version) and exits immediately after writing this. A child that
/// exits WITHOUT a FatalError crashed hard (segfault, abort, kill) — parents
/// must treat EOF as a crash.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FatalError {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MountMode {
    Unspecified = 0,
    ReadOnly = 1,
    ReadWrite = 2,
    /// Copy-on-write overlay backed by child-local memory; writes are discarded
    /// when the session ends.
    Overlay = 3,
}
impl MountMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MOUNT_MODE_UNSPECIFIED",
            Self::ReadOnly => "MOUNT_MODE_READ_ONLY",
            Self::ReadWrite => "MOUNT_MODE_READ_WRITE",
            Self::Overlay => "MOUNT_MODE_OVERLAY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MOUNT_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "MOUNT_MODE_READ_ONLY" => Some(Self::ReadOnly),
            "MOUNT_MODE_READ_WRITE" => Some(Self::ReadWrite),
            "MOUNT_MODE_OVERLAY" => Some(Self::Overlay),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PrintStream {
    Unspecified = 0,
    Stdout = 1,
    Stderr = 2,
}
impl PrintStream {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PRINT_STREAM_UNSPECIFIED",
            Self::Stdout => "PRINT_STREAM_STDOUT",
            Self::Stderr => "PRINT_STREAM_STDERR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PRINT_STREAM_UNSPECIFIED" => Some(Self::Unspecified),
            "PRINT_STREAM_STDOUT" => Some(Self::Stdout),
            "PRINT_STREAM_STDERR" => Some(Self::Stderr),
            _ => None,
        }
    }
}
